### PR TITLE
Revamp RabbitMQ provider

### PR DESCRIPTION
**Pull request by galvesribeiro**
- Updated to `netstandard2.0`
- Added extension methods to configure the provider 
- Updated to latest Orleans 2.0 Beta 3
- Updated to latest stable version of the RabbitMQ client
- Some fixes around the code 
- Added CircleCI
- Added Nuget publishing when merging to master

This still experimental. I'm going to spend some time to complete the provider implementation soon. For now at least it is minimally usable for tests.

NOTE: Please ignore the AppVeyor build status. After this PR is merged it will be fixed.

### CODE REVIEW

**Comment by creyke** [comment]
Including @bobanco for visibility.

**Review by creyke — APPROVED** [review]
LGTM - looks like progress, and no obvious issues.

**Comment by galvesribeiro** [comment]
I'm adding few improvements on this same PR. Nothing big, just adding support to read/write only streams and support to other rabbit settings.

**Comment by galvesribeiro** [comment]
I'm merging it as it completed the PR purpose. I'm going to add the other enhancements in another PR.

**Pull request merged**
