### PR TITLE
Depend on netstandard instead of netcore for better compatibility

### PR DESCRIPTION
**Pull request by henrik-m**

### CODE REVIEW

**Comment by henrik-m** [comment]
AppVeyor doesn't seem to like the new csproj format. Is this a configuration issue? The build fails also on the master branch.

**Comment by richorama** [comment]
@henrik-m have you tried switching to the latest build worker image in app veyor?

screenshot 2017-09-08 09 33 17

**Comment by henrik-m** [comment]
@richorama Maybe that is the issue, but I have no control over the AppVeyor settings for this repository. That would have to be fixed by @creyke I guess

**Comment by creyke** [comment]
Did not know build server was set up...

**Pull request merged**
